### ISSUE TITLE
Configure Parse Server

### ISSUE THREAD

**Issue by yaminiPonugoti** [CS490-MentorMate/MentorMate#9]
Reference Configure Parse Server Guide - iOS
- [x] Configure to AWS

- [x]  Test deployment

- [x]   Setup local Parse Dashboard

- [x]  Add Parse Client to Project

**Comment by santos50** [comment]
Issue is good. Parse dashboard can be accessed at ec2-18-188-52-128.us-east-2.compute.amazonaws.com/app
